// AUTOGENERATED - DO NOT MODIFY

// View component imports — one per viewport declared in ui_extension.views
import SettingsView from '../src/views/SettingsView';
import InvoiceDetailView from '../src/views/InvoiceDetailView';

// Exposes the SDK version so the Dashboard can verify compatibility
export * from '@stripe/ui-extension-sdk/version';

// Named exports make each view component accessible to the Dashboard runtime

export { 
  SettingsView,

  InvoiceDetailView
 };

// Timestamp changes on every export, ensuring the dev server detects a rebuild
export const BUILD_TIME = '2026-08-05 16:42:18.577036349 +0000 UTC m=+2.451285717';

// App manifest — consumed by the Dashboard to configure the app
export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "icon": "./icon.png",
  "id": "com.stripecollectionscopilot.app",
  "name": "Stripe Collections Copilot",
  "permissions": [
    {
      "permission": "invoice_read",
      "purpose": ""
    },
    {
      "permission": "customer_read",
      "purpose": ""
    }
  ],
  "ui_extension": {
    "views": [
      {
        "component": "SettingsView",
        "viewport": "stripe.dashboard.drawer.default"
      },
      {
        "component": "InvoiceDetailView",
        "viewport": "stripe.dashboard.invoice.detail"
      }
    ]
  },
  "version": "0.1.0"
};
